/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kalkulator;

/**
 *
 * @author Hp
 */
public class Kalkulator extends javax.swing.JFrame {
    String angka;
    Double angka1, angka2, jumlah;
    int pilih;
    
    
        
    

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfhasil = new javax.swing.JTextField();
        ButtonC = new javax.swing.JButton();
        Buttonsamadengan = new javax.swing.JButton();
        Buttonakar = new javax.swing.JButton();
        Buttonbagi = new javax.swing.JButton();
        Buttonpersen = new javax.swing.JButton();
        Buttonkali = new javax.swing.JButton();
        Buttonperx = new javax.swing.JButton();
        Buttontambah = new javax.swing.JButton();
        Buttonplusmin = new javax.swing.JButton();
        Buttonkurang = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Buttontitik = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Buttonhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        tfhasil.setEditable(false);
        tfhasil.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhasilActionPerformed(evt);
            }
        });
        jPanel1.add(tfhasil);
        tfhasil.setBounds(10, 10, 290, 90);

        ButtonC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonC.setText("C");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonC);
        ButtonC.setBounds(70, 110, 60, 40);

        Buttonsamadengan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttonsamadengan.setText("=");
        Buttonsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsamadenganActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonsamadengan);
        Buttonsamadengan.setBounds(250, 260, 50, 100);

        Buttonakar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttonakar.setText("√");
        Buttonakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonakarActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonakar);
        Buttonakar.setBounds(250, 110, 50, 40);

        Buttonbagi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttonbagi.setText("/");
        Buttonbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonbagiActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonbagi);
        Buttonbagi.setBounds(200, 160, 50, 50);

        Buttonpersen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttonpersen.setText("%");
        Buttonpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpersenActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonpersen);
        Buttonpersen.setBounds(250, 160, 50, 50);

        Buttonkali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttonkali.setText("X");
        Buttonkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonkaliActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonkali);
        Buttonkali.setBounds(200, 210, 50, 50);

        Buttonperx.setText("1/X");
        Buttonperx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonperxActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonperx);
        Buttonperx.setBounds(250, 210, 50, 50);

        Buttontambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttontambah.setText("+");
        Buttontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtontambahActionPerformed(evt);
            }
        });
        jPanel1.add(Buttontambah);
        Buttontambah.setBounds(200, 310, 50, 50);

        Buttonplusmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttonplusmin.setText("±");
        Buttonplusmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonplusminActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonplusmin);
        Buttonplusmin.setBounds(200, 110, 50, 40);

        Buttonkurang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttonkurang.setText("-");
        Buttonkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonkurangActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonkurang);
        Buttonkurang.setBounds(200, 260, 50, 50);

        Button0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        jPanel1.add(Button0);
        Button0.setBounds(10, 310, 120, 50);

        Button9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        jPanel1.add(Button9);
        Button9.setBounds(130, 160, 60, 50);

        Button4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        jPanel1.add(Button4);
        Button4.setBounds(10, 210, 60, 50);

        Button5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        jPanel1.add(Button5);
        Button5.setBounds(70, 210, 60, 50);

        Button6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        jPanel1.add(Button6);
        Button6.setBounds(130, 210, 60, 50);

        Button1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1);
        Button1.setBounds(10, 260, 60, 50);

        Button2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel1.add(Button2);
        Button2.setBounds(70, 260, 60, 50);

        Button3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        jPanel1.add(Button3);
        Button3.setBounds(130, 260, 60, 50);

        Button7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        jPanel1.add(Button7);
        Button7.setBounds(10, 160, 60, 50);

        Buttontitik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Buttontitik.setText(".");
        Buttontitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtontitikActionPerformed(evt);
            }
        });
        jPanel1.add(Buttontitik);
        Buttontitik.setBounds(130, 310, 60, 50);

        Button8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        jPanel1.add(Button8);
        Button8.setBounds(70, 160, 60, 50);

        Buttonhapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Buttonhapus.setText("<==");
        Buttonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonhapusActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonhapus);
        Buttonhapus.setBounds(10, 110, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 380);

        setBounds(0, 0, 326, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void tfhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhasilActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfhasilActionPerformed

    private void ButtonsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsamadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 + angka2;
                angka = Double.toString(jumlah);
                tfhasil.setText(angka);
                break;
            case 2:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 - angka2;
                angka = Double.toString(jumlah);
                tfhasil.setText(angka);
                break;
            case 3:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 * angka2;
                angka = Double.toString(jumlah);
                tfhasil.setText(angka);
                break;
            case 4:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 / angka2;
                angka = Double.toString(jumlah);
                tfhasil.setText(angka);
                break;
            case 5:
                jumlah = angka1/100;
                angka = Double.toString(jumlah);
                tfhasil.setText(angka);
                break;
            case 6 :
                jumlah = Math.sqrt(angka1);
                angka = Double.toString(jumlah);
                tfhasil.setText(angka);
                break;
            case 7 :
                jumlah = 1/angka1 ;
                angka = Double.toString(jumlah);
                tfhasil.setText(angka);
                break;
            
                
           
        }
                
            
        
    }//GEN-LAST:event_ButtonsamadenganActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        tfhasil.setText(angka);
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        // TODO add your handling code here:
       tfhasil.setText("");
       angka1 = 0.0;
       angka2 = 0.0;
       jumlah = 0.0;
       angka = "";
            
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtontambahActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tfhasil.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_ButtontambahActionPerformed

    private void ButtonkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonkurangActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tfhasil.setText("-");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_ButtonkurangActionPerformed

    private void ButtonkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonkaliActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tfhasil.setText("*");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_ButtonkaliActionPerformed

    private void ButtonbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonbagiActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tfhasil.setText("/");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_ButtonbagiActionPerformed

    private void ButtonperxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonperxActionPerformed
        // TODO add your handling code here:
        
        angka1 = Double.parseDouble(angka);
        tfhasil.setText("1/x");
        angka = "";
        pilih = 7;
    }//GEN-LAST:event_ButtonperxActionPerformed

    private void ButtonpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpersenActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tfhasil.setText("%");
        angka = "";
        pilih = 5;
    }//GEN-LAST:event_ButtonpersenActionPerformed

    private void ButtonakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonakarActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        tfhasil.setText("√");
        angka = "";
        pilih = 6;
    }//GEN-LAST:event_ButtonakarActionPerformed

    private void ButtontitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtontitikActionPerformed
        // TODO add your handling code here:
        angka += ".";
        tfhasil.setText(angka);
    }//GEN-LAST:event_ButtontitikActionPerformed

    private void ButtonplusminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonplusminActionPerformed
        // TODO add your handling code here:
       if(!angka.contains("-"))
           angka = "-" +angka;
       else 
           angka = angka.substring(1, angka.length());
       tfhasil.setText(angka);
    }//GEN-LAST:event_ButtonplusminActionPerformed

    private void ButtonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonhapusActionPerformed
        // TODO add your handling code here:
        angka = angka.substring(0, angka.length() -1);
        tfhasil.setText(angka);
            
    }//GEN-LAST:event_ButtonhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton Buttonakar;
    private javax.swing.JButton Buttonbagi;
    private javax.swing.JButton Buttonhapus;
    private javax.swing.JButton Buttonkali;
    private javax.swing.JButton Buttonkurang;
    private javax.swing.JButton Buttonpersen;
    private javax.swing.JButton Buttonperx;
    private javax.swing.JButton Buttonplusmin;
    private javax.swing.JButton Buttonsamadengan;
    private javax.swing.JButton Buttontambah;
    private javax.swing.JButton Buttontitik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfhasil;
    // End of variables declaration//GEN-END:variables
}
